### PR TITLE
Add ryan as an owner of the cluster api repo

### PR DESCRIPTION
**Pull request by ryanzhang-oss**

### CODE REVIEW

**Review by dixudx — APPROVED** [review]

**Comment by RainbowMango** [comment]
/lgtm

> ryanzhang-oss
User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

I see @dixudx removed the `do-not-merge/invalid-owners-file` label, just out of curiosity, what would happen if an owner is not org member?

**Comment by dixudx** [comment]
@RainbowMango Ryan(ryanzhang-oss) is an org member, please refer to kubernetes/org#4816.

**Pull request merged**
